### ISSUE TITLE
allow user to choose parquet vs csv.gz ?

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/XeniumIO#2]

**Comment by alikhuseynov** [comment]
I think this would depend which file would be faster to read.

**Comment by LiNk-NY** [comment]
I'd have to run benchmarks with different tools. For now, I think I will allow the user to choose either `read.csv` or `arrow::read_parquet`

**Comment by alikhuseynov** [comment]
`data.table::fread` would be the fastest especially for large .csv files
